name: challenge_diabetes
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  dash_chat_2: ^0.0.21
  fl_chart: ^0.68.0
  flutter_localization: ^0.2.1
  iconsax_flutter: ^1.0.0
  image_picker: ^1.1.2
  easy_date_timeline: ^1.1.3
  intl: ^0.19.0
  camera: ^0.11.0+2
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  jwt_decoder: ^2.0.1
  uuid: ^4.4.2
  firebase_messaging: ^15.0.4
  percent_indicator: ^4.0.1

  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  shared_preferences: ^2.3.1
  flutter_bloc: ^8.1.6
  fluttertoast: ^8.2.6
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  flutter_datetime_picker: ^1.5.1
  image_stack: ^2.1.1
  firebase_storage: ^12.1.3
  flutter_svg: ^2.0.10+1
  google_generative_ai: ^0.4.4
  wakelock_plus: ^1.2.7
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  dio: ^5.4.3+1
  smooth_page_indicator: ^1.1.0
  flutter_lints: ^4.0.0
flutter:

 
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

