// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Lwo37nw2Gqx4Bjes4msGglsZ6MpVspI',
    appId: '1:495839621726:web:e059facaa2ef257f93facf',
    messagingSenderId: '495839621726',
    projectId: 'gluco-chat',
    authDomain: 'gluco-chat.firebaseapp.com',
    storageBucket: 'gluco-chat.appspot.com',
    measurementId: 'G-1R65G3WT2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7OfiKJVl2IRy3bfkqSPBFxZsN421rfvI',
    appId: '1:495839621726:android:5e44faa9d662628a93facf',
    messagingSenderId: '495839621726',
    projectId: 'gluco-chat',
    storageBucket: 'gluco-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC68j68YiDDRyZmgVoCuvw00YrIaYL954',
    appId: '1:495839621726:ios:31e1b78334f213f393facf',
    messagingSenderId: '495839621726',
    projectId: 'gluco-chat',
    storageBucket: 'gluco-chat.appspot.com',
    iosBundleId: 'com.example.gluco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC68j68YiDDRyZmgVoCuvw00YrIaYL954',
    appId: '1:495839621726:ios:31e1b78334f213f393facf',
    messagingSenderId: '495839621726',
    projectId: 'gluco-chat',
    storageBucket: 'gluco-chat.appspot.com',
    iosBundleId: 'com.example.gluco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3Lwo37nw2Gqx4Bjes4msGglsZ6MpVspI',
    appId: '1:495839621726:web:3a727a1217adcf8b93facf',
    messagingSenderId: '495839621726',
    projectId: 'gluco-chat',
    authDomain: 'gluco-chat.firebaseapp.com',
    storageBucket: 'gluco-chat.appspot.com',
    measurementId: 'G-8KF31CS9VC',
  );
}
